[package]
name = "sir-stack-scheduling"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sir-data.workspace = true
sir-passes.workspace = true
plank-core.workspace = true
hashbrown.workspace = true
smallvec.workspace = true
rayon.workspace = true
sha2.workspace = true

[dev-dependencies]
plank-test-utils.workspace = true
pretty_assertions.workspace = true
sir-parser.workspace = true
sir-stack-scheduling-db-inspect = { path = "../../../devtools/stack-scheduling-db-inspect" }
proptest.workspace = true

[lints]
workspace = true
