use sensei_parser::PlankInterner;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Builtins {
    // ========== EVM Arithmetic ==========
    Add,
    Mul,
    Sub,
    Div,
    SDiv,
    Mod,
    SMod,
    AddMod,
    MulMod,
    Exp,
    SignExtend,

    // ========== EVM Comparison & Bitwise Logic ==========
    Lt,
    Gt,
    SLt,
    SGt,
    Eq,
    IsZero,
    And,
    Or,
    Xor,
    Not,
    Byte,
    Shl,
    Shr,
    Sar,

    // ========== EVM Keccak-256 ==========
    Keccak256,

    // ========== EVM Environment Information ==========
    Address,
    Balance,
    Origin,
    Caller,
    CallValue,
    CallDataLoad,
    CallDataSize,
    CallDataCopy,
    CodeSize,
    CodeCopy,
    GasPrice,
    ExtCodeSize,
    ExtCodeCopy,
    ReturnDataSize,
    ReturnDataCopy,
    ExtCodeHash,
    Gas,

    // ========== EVM Block Information ==========
    BlockHash,
    Coinbase,
    Timestamp,
    Number,
    Difficulty,
    GasLimit,
    ChainId,
    SelfBalance,
    BaseFee,
    BlobHash,
    BlobBaseFee,

    // ========== EVM State Manipulation ==========
    SLoad,
    SStore,
    TLoad,
    TStore,

    // ========== EVM Logging Operations ==========
    Log0,
    Log1,
    Log2,
    Log3,
    Log4,

    // ========== EVM System Calls ==========
    Create,
    Create2,
    Call,
    CallCode,
    DelegateCall,
    StaticCall,
    Return,
    Stop,
    Revert,
    Invalid,
    SelfDestruct,

    // ========== IR Memory Primitives ==========
    DynamicAllocZeroed,
    DynamicAllocAnyBytes,

    // ========== Memory Manipulation ==========
    MemoryCopy,
    MLoad1,
    MLoad2,
    MLoad3,
    MLoad4,
    MLoad5,
    MLoad6,
    MLoad7,
    MLoad8,
    MLoad9,
    MLoad10,
    MLoad11,
    MLoad12,
    MLoad13,
    MLoad14,
    MLoad15,
    MLoad16,
    MLoad17,
    MLoad18,
    MLoad19,
    MLoad20,
    MLoad21,
    MLoad22,
    MLoad23,
    MLoad24,
    MLoad25,
    MLoad26,
    MLoad27,
    MLoad28,
    MLoad29,
    MLoad30,
    MLoad31,
    MLoad32,
    MStore1,
    MStore2,
    MStore3,
    MStore4,
    MStore5,
    MStore6,
    MStore7,
    MStore8,
    MStore9,
    MStore10,
    MStore11,
    MStore12,
    MStore13,
    MStore14,
    MStore15,
    MStore16,
    MStore17,
    MStore18,
    MStore19,
    MStore20,
    MStore21,
    MStore22,
    MStore23,
    MStore24,
    MStore25,
    MStore26,
    MStore27,
    MStore28,
    MStore29,
    MStore30,
    MStore31,
    MStore32,

    // ========== Bytecode Introspection ==========
    RuntimeStartOffset,
    InitEndOffset,
    RuntimeLength,
}

impl Builtins {
    pub fn from_str_id(str_id: sensei_parser::StrId) -> Option<Self> {
        Some(match str_id {
            // ========== EVM Arithmetic ==========
            PlankInterner::ADD => Builtins::Add,
            PlankInterner::MUL => Builtins::Mul,
            PlankInterner::SUB => Builtins::Sub,
            PlankInterner::DIV => Builtins::Div,
            PlankInterner::SDIV => Builtins::SDiv,
            PlankInterner::MOD => Builtins::Mod,
            PlankInterner::SMOD => Builtins::SMod,
            PlankInterner::ADDMOD => Builtins::AddMod,
            PlankInterner::MULMOD => Builtins::MulMod,
            PlankInterner::EXP => Builtins::Exp,
            PlankInterner::SIGNEXTEND => Builtins::SignExtend,

            // ========== EVM Comparison & Bitwise Logic ==========
            PlankInterner::LT => Builtins::Lt,
            PlankInterner::GT => Builtins::Gt,
            PlankInterner::SLT => Builtins::SLt,
            PlankInterner::SGT => Builtins::SGt,
            PlankInterner::EQ => Builtins::Eq,
            PlankInterner::ISZERO => Builtins::IsZero,
            PlankInterner::AND => Builtins::And,
            PlankInterner::OR => Builtins::Or,
            PlankInterner::XOR => Builtins::Xor,
            PlankInterner::NOT => Builtins::Not,
            PlankInterner::BYTE => Builtins::Byte,
            PlankInterner::SHL => Builtins::Shl,
            PlankInterner::SHR => Builtins::Shr,
            PlankInterner::SAR => Builtins::Sar,

            // ========== EVM Keccak-256 ==========
            PlankInterner::KECCAK256 => Builtins::Keccak256,

            // ========== EVM Environment Information ==========
            PlankInterner::ADDRESS => Builtins::Address,
            PlankInterner::BALANCE => Builtins::Balance,
            PlankInterner::ORIGIN => Builtins::Origin,
            PlankInterner::CALLER => Builtins::Caller,
            PlankInterner::CALLVALUE => Builtins::CallValue,
            PlankInterner::CALLDATALOAD => Builtins::CallDataLoad,
            PlankInterner::CALLDATASIZE => Builtins::CallDataSize,
            PlankInterner::CALLDATACOPY => Builtins::CallDataCopy,
            PlankInterner::CODESIZE => Builtins::CodeSize,
            PlankInterner::CODECOPY => Builtins::CodeCopy,
            PlankInterner::GASPRICE => Builtins::GasPrice,
            PlankInterner::EXTCODESIZE => Builtins::ExtCodeSize,
            PlankInterner::EXTCODECOPY => Builtins::ExtCodeCopy,
            PlankInterner::RETURNDATASIZE => Builtins::ReturnDataSize,
            PlankInterner::RETURNDATACOPY => Builtins::ReturnDataCopy,
            PlankInterner::EXTCODEHASH => Builtins::ExtCodeHash,
            PlankInterner::GAS => Builtins::Gas,

            // ========== EVM Block Information ==========
            PlankInterner::BLOCKHASH => Builtins::BlockHash,
            PlankInterner::COINBASE => Builtins::Coinbase,
            PlankInterner::TIMESTAMP => Builtins::Timestamp,
            PlankInterner::NUMBER => Builtins::Number,
            PlankInterner::DIFFICULTY => Builtins::Difficulty,
            PlankInterner::GASLIMIT => Builtins::GasLimit,
            PlankInterner::CHAINID => Builtins::ChainId,
            PlankInterner::SELFBALANCE => Builtins::SelfBalance,
            PlankInterner::BASEFEE => Builtins::BaseFee,
            PlankInterner::BLOBHASH => Builtins::BlobHash,
            PlankInterner::BLOBBASEFEE => Builtins::BlobBaseFee,

            // ========== EVM State Manipulation ==========
            PlankInterner::SLOAD => Builtins::SLoad,
            PlankInterner::SSTORE => Builtins::SStore,
            PlankInterner::TLOAD => Builtins::TLoad,
            PlankInterner::TSTORE => Builtins::TStore,

            // ========== EVM Logging Operations ==========
            PlankInterner::LOG0 => Builtins::Log0,
            PlankInterner::LOG1 => Builtins::Log1,
            PlankInterner::LOG2 => Builtins::Log2,
            PlankInterner::LOG3 => Builtins::Log3,
            PlankInterner::LOG4 => Builtins::Log4,

            // ========== EVM System Calls ==========
            PlankInterner::CREATE => Builtins::Create,
            PlankInterner::CREATE2 => Builtins::Create2,
            PlankInterner::CALL => Builtins::Call,
            PlankInterner::CALLCODE => Builtins::CallCode,
            PlankInterner::DELEGATECALL => Builtins::DelegateCall,
            PlankInterner::STATICCALL => Builtins::StaticCall,
            PlankInterner::RETURN => Builtins::Return,
            PlankInterner::STOP => Builtins::Stop,
            PlankInterner::REVERT => Builtins::Revert,
            PlankInterner::INVALID => Builtins::Invalid,
            PlankInterner::SELFDESTRUCT => Builtins::SelfDestruct,

            // ========== IR Memory Primitives ==========
            PlankInterner::DYNAMIC_ALLOC_ZEROED => Builtins::DynamicAllocZeroed,
            PlankInterner::DYNAMIC_ALLOC_ANY_BYTES => Builtins::DynamicAllocAnyBytes,

            // ========== Memory Manipulation ==========
            PlankInterner::MEMORY_COPY => Builtins::MemoryCopy,
            PlankInterner::MLOAD1 => Builtins::MLoad1,
            PlankInterner::MLOAD2 => Builtins::MLoad2,
            PlankInterner::MLOAD3 => Builtins::MLoad3,
            PlankInterner::MLOAD4 => Builtins::MLoad4,
            PlankInterner::MLOAD5 => Builtins::MLoad5,
            PlankInterner::MLOAD6 => Builtins::MLoad6,
            PlankInterner::MLOAD7 => Builtins::MLoad7,
            PlankInterner::MLOAD8 => Builtins::MLoad8,
            PlankInterner::MLOAD9 => Builtins::MLoad9,
            PlankInterner::MLOAD10 => Builtins::MLoad10,
            PlankInterner::MLOAD11 => Builtins::MLoad11,
            PlankInterner::MLOAD12 => Builtins::MLoad12,
            PlankInterner::MLOAD13 => Builtins::MLoad13,
            PlankInterner::MLOAD14 => Builtins::MLoad14,
            PlankInterner::MLOAD15 => Builtins::MLoad15,
            PlankInterner::MLOAD16 => Builtins::MLoad16,
            PlankInterner::MLOAD17 => Builtins::MLoad17,
            PlankInterner::MLOAD18 => Builtins::MLoad18,
            PlankInterner::MLOAD19 => Builtins::MLoad19,
            PlankInterner::MLOAD20 => Builtins::MLoad20,
            PlankInterner::MLOAD21 => Builtins::MLoad21,
            PlankInterner::MLOAD22 => Builtins::MLoad22,
            PlankInterner::MLOAD23 => Builtins::MLoad23,
            PlankInterner::MLOAD24 => Builtins::MLoad24,
            PlankInterner::MLOAD25 => Builtins::MLoad25,
            PlankInterner::MLOAD26 => Builtins::MLoad26,
            PlankInterner::MLOAD27 => Builtins::MLoad27,
            PlankInterner::MLOAD28 => Builtins::MLoad28,
            PlankInterner::MLOAD29 => Builtins::MLoad29,
            PlankInterner::MLOAD30 => Builtins::MLoad30,
            PlankInterner::MLOAD31 => Builtins::MLoad31,
            PlankInterner::MLOAD32 => Builtins::MLoad32,
            PlankInterner::MSTORE1 => Builtins::MStore1,
            PlankInterner::MSTORE2 => Builtins::MStore2,
            PlankInterner::MSTORE3 => Builtins::MStore3,
            PlankInterner::MSTORE4 => Builtins::MStore4,
            PlankInterner::MSTORE5 => Builtins::MStore5,
            PlankInterner::MSTORE6 => Builtins::MStore6,
            PlankInterner::MSTORE7 => Builtins::MStore7,
            PlankInterner::MSTORE8 => Builtins::MStore8,
            PlankInterner::MSTORE9 => Builtins::MStore9,
            PlankInterner::MSTORE10 => Builtins::MStore10,
            PlankInterner::MSTORE11 => Builtins::MStore11,
            PlankInterner::MSTORE12 => Builtins::MStore12,
            PlankInterner::MSTORE13 => Builtins::MStore13,
            PlankInterner::MSTORE14 => Builtins::MStore14,
            PlankInterner::MSTORE15 => Builtins::MStore15,
            PlankInterner::MSTORE16 => Builtins::MStore16,
            PlankInterner::MSTORE17 => Builtins::MStore17,
            PlankInterner::MSTORE18 => Builtins::MStore18,
            PlankInterner::MSTORE19 => Builtins::MStore19,
            PlankInterner::MSTORE20 => Builtins::MStore20,
            PlankInterner::MSTORE21 => Builtins::MStore21,
            PlankInterner::MSTORE22 => Builtins::MStore22,
            PlankInterner::MSTORE23 => Builtins::MStore23,
            PlankInterner::MSTORE24 => Builtins::MStore24,
            PlankInterner::MSTORE25 => Builtins::MStore25,
            PlankInterner::MSTORE26 => Builtins::MStore26,
            PlankInterner::MSTORE27 => Builtins::MStore27,
            PlankInterner::MSTORE28 => Builtins::MStore28,
            PlankInterner::MSTORE29 => Builtins::MStore29,
            PlankInterner::MSTORE30 => Builtins::MStore30,
            PlankInterner::MSTORE31 => Builtins::MStore31,
            PlankInterner::MSTORE32 => Builtins::MStore32,

            // ========== Bytecode Introspection ==========
            PlankInterner::RUNTIME_START_OFFSET => Builtins::RuntimeStartOffset,
            PlankInterner::INIT_END_OFFSET => Builtins::InitEndOffset,
            PlankInterner::RUNTIME_LENGTH => Builtins::RuntimeLength,

            _ => return None,
        })
    }
}
