default: check test

fmt:
    cargo +nightly fmt --all

check: fmt
    cargo +nightly clippy --workspace --all-targets --all-features -- -D warnings -A dead_code

test:
    cargo test --workspace

[working-directory: 'sir/sir-solidity-diff-tests']
test-sir-diff:
     forge test --ffi

[working-directory: 'plank-diff-tests/']
test-plank-diff: test-plank-diff-sir test-plank-diff-sona

[working-directory: 'plank-diff-tests/']
test-plank-diff-sir:
     PLANK_BACKEND=sir PLANK_OPTIMIZE= forge test --ffi
     PLANK_BACKEND=sir PLANK_OPTIMIZE=csud forge test --ffi

[working-directory: 'plank-diff-tests/']
test-plank-diff-sona:
     PLANK_BACKEND=sona PLANK_OPTIMIZE= forge test --ffi
     PLANK_BACKEND=sona PLANK_OPTIMIZE=O1 forge test --ffi

test-all: test test-sir-diff test-plank-diff

ci-fmt:
    (cd sir/sir-solidity-diff-tests/ && forge fmt --check)
    cargo +nightly fmt --all --check

ci-clippy:
    cargo +nightly clippy --workspace --all-targets --all-features -- -D warnings

ci-all: test-all ci-clippy ci-fmt

docs-build:
    mdbook build ../plank-doc -d ~/.plank/share/doc

docs-serve:
    mdbook serve ../plank-doc
