default: check test

build-debug:
    cargo build -p plank

link-dev-local: build-debug
    mkdir -p "$HOME/.plank/bin"
    rm -rf "$HOME/.plank/bin/plank" "$HOME/.plank/stdlib"
    ln -s "$PWD/../std" "$HOME/.plank/stdlib"
    ln -s "$PWD/target/debug/plank" "$HOME/.plank/bin/plank"

fmt:
    cargo +nightly fmt --all

check: fmt
    cargo +nightly clippy --workspace --all-targets --all-features -- -D warnings -A dead_code

test:
    cargo nextest run --workspace

[working-directory: 'sir/sir-solidity-diff-tests']
test-sir-diff:
     SIR_RELEASE_BACKEND=0 forge test --ffi
     SIR_RELEASE_BACKEND=1 forge test --ffi

test-plank-diff: test-plank-diff-sir test-plank-diff-sona

[working-directory: 'plank-diff-tests/']
test-plank-diff-sir: build-debug
     PLANK_BACKEND=sir-debug   PLANK_OPTIMIZE=     forge test --nmp test/benchmark/*
     PLANK_BACKEND=sir-debug   PLANK_OPTIMIZE=csud forge test --nmp test/benchmark/*
     PLANK_BACKEND=sir-release PLANK_OPTIMIZE=     forge test --nmp test/benchmark/*
     PLANK_BACKEND=sir-release PLANK_OPTIMIZE=csud forge test --nmp test/benchmark/*

[working-directory: 'plank-diff-tests/']
test-plank-diff-sona: build-debug
     PLANK_BACKEND=sona PLANK_OPTIMIZE=   forge test --nmp test/benchmark/*
     PLANK_BACKEND=sona PLANK_OPTIMIZE=O1 forge test --nmp test/benchmark/*

[working-directory: 'plank-diff-tests/']
bytecode-bench: build-debug
    forge test --mp test/benchmark/* --gas-snapshot-check true

test-all: test test-sir-diff test-plank-diff bytecode-bench

ci-fmt:
    (cd sir/sir-solidity-diff-tests/ && forge fmt --check)
    cargo +nightly fmt --all --check

ci-clippy:
    cargo +nightly clippy --workspace --all-targets --all-features -- -D warnings

ci-all: test-all ci-clippy ci-fmt

docs-build:
    mdbook build ../plank-doc -d ~/.plank/share/doc

docs-serve:
    mdbook serve ../plank-doc
